package com.example.ui

object Locales {
    val en = mapOf(
        "library" to "Library",
        "settings" to "Settings",
        "analytics" to "Analytics",
        "add_book" to "Add Title",
        "edit_book" to "Edit Title",
        "share" to "Share",
        "planned" to "Planned",
        "reading" to "Reading",
        "paused" to "Paused",
        "completed" to "Completed",
        "dropped" to "Dropped",
        "search" to "Search titles...",
        "no_books" to "No titles in the library",
        "export_library" to "Export Library",
        "import_library" to "Import Library",
        "export_settings" to "Export Settings",
        "import_settings" to "Import Settings",
        "appearance" to "Appearance",
        "data" to "Data",
        "configuration" to "Configuration",
        "application" to "Application",
        "language" to "Language",
        "font_size_library" to "Header Font Size",
        "font_size_library_sub" to "Font size setting for screen header",
        "theme" to "Theme",
        "theme_light" to "Light",
        "theme_dark" to "Dark",
        "theme_system" to "System",
        "accent_color" to "Accent Color",
        "save" to "Save",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "import" to "Import",
        "confirm_import_books" to "The current library will be replaced by the library from the file.",
        "confirm_import_settings" to "All current app settings will be replaced by settings from the file.",
        "stats" to "Statistics",
        "total_books" to "Total Titles",
        "pages_read" to "Pages Read",
        "chapters_read" to "Chapters Read",
        "color_settings" to "Color Settings",
        "color_customization" to "Color Customization",
        "color_customization_sub" to "Configure UI, types and status colors",
        "advanced_functions" to "Advanced Functions",
        "bookmarks" to "Bookmarks",
        "bookmarks_sub_on" to "Chapter entry field without affecting stats",
        "bookmarks_sub_off" to "Notes field disabled",
        "bookmark_position" to "Bookmark Position",
        "bookmark_position_sub" to "Position of current bookmark in the list",
        "bottom" to "Bottom",
        "inline" to "Inline",
        "read_after_adaptation" to "Read after Adaptation",
        "read_after_adaptation_sub_on" to "Ability to specify start vol/ch",
        "read_after_adaptation_sub_off" to "Feature disabled",
        "hybrid_format" to "Hybrid Format LN+WN",
        "hybrid_format_sub_on" to "Combine LN and WN in one card",
        "hybrid_format_sub_off" to "Separate cards for volumes and chapters",
        "title_rating" to "Title Rating",
        "title_rating_sub_on" to "Enable rating for titles",
        "title_rating_sub_off" to "Rating feature disabled",
        "rating_scale" to "Rating Scale",
        "rating_scale_sub" to "Assessment scale graduation tool",
        "stars_5" to "5 Stars",
        "stars_10" to "10 Stars",
        "rating_placement" to "Rating & Type Placement",
        "rating_placement_sub" to "Choose how to place rating and type on card",
        "column" to "Column",
        "row" to "Row",
        "show_in_analytics" to "Show in Analytics",
        "show_in_analytics_sub" to "Choose which types to display in reports",
        "singles_and_web" to "Singles & Web",
        "only_singles" to "Only Singles",
        "only_web" to "Only Web",
        "hidden" to "Hidden",
        "title_covers" to "Title Covers",
        "title_covers_sub_on" to "Show covers in list",
        "title_covers_sub_off" to "Compact view without covers",
        "shorten_numbers" to "Shorten Numbers",
        "shorten_numbers_sub" to "Example: 150K instead of 150 000",
        "stacked_analytics" to "Stacked Analytics",
        "stacked_analytics_sub" to "Stack analytics metrics vertically",
        "share_button" to "Share Button",
        "share_button_sub" to "Display share button in library header",
        "chapters_for_web" to "Chapters for Web Novels",
        "chapters_for_web_sub_on" to "Show X/Y ch. on cards",
        "chapters_for_web_sub_off" to "Chapter progress hidden in list",
        "disable_animations" to "Disable Animations",
        "disable_animations_sub_on" to "Transition animations disabled",
        "disable_animations_sub_off" to "Smooth transitions between pages",
        "header_spacing" to "Header to Filters spacing",
        "header_spacing_sub" to "Spacing between 'Library' and tabs",
        "card_spacing" to "Card Spacing",
        "card_spacing_sub" to "Adjust line height and spacing inside cards",
        "title_font_size" to "Title Font Size",
        "title_font_size_sub" to "Adjust font size for title in card",
        "reset_all" to "Reset All",
        "reset_to_default" to "Reset all colors to default",
        "color_reset_title" to "Reset Color Scheme",
        "color_reset_confirm" to "Are you sure you want to reset all custom colors to default?",
        "reset" to "Reset",
        "close" to "Close",
        "interface_colors" to "Interface Colors",
        "accent_and_buttons" to "Accent and buttons",
        "edition_types" to "Edition Types",
        "reading_statuses" to "Reading Statuses",
        "flexible_customization" to "Flexible Customization",
        "customization_sub" to "Tap the color circle to pick from palette or enter HEX manually.",
        "pick_color" to "Choose Color",
        "pick_from_palette" to "Select from preset palette:",
        "save_to_json" to "Save to JSON file",
        "load_from_json" to "Load from JSON file",
        "save_configuration" to "Save current configuration",
        "load_configuration" to "Load configuration from file",
        "stats_card" to "Statistics card",
        "title_list" to "Title list",
        "all_titles_card" to "All titles on one card"
    )

    val ru = mapOf(
        "library" to "Библиотека",
        "settings" to "Настройки",
        "analytics" to "Аналитика",
        "add_book" to "Добавить тайтл",
        "edit_book" to "Редактировать тайтл",
        "share" to "Поделиться",
        "planned" to "Планирую",
        "reading" to "Читаю",
        "paused" to "На паузе",
        "completed" to "Прочитано",
        "dropped" to "Брошено",
        "search" to "Поиск тайтлов...",
        "no_books" to "В библиотеке нет тайтлов",
        "export_library" to "Экспорт библиотеки",
        "import_library" to "Импорт библиотеки",
        "export_settings" to "Экспорт настроек",
        "import_settings" to "Импорт настроек",
        "appearance" to "Отображение",
        "data" to "Данные",
        "configuration" to "Конфигурация",
        "application" to "Приложение",
        "language" to "Язык",
        "font_size_library" to "Размер заголовка",
        "font_size_library_sub" to "Настройка размера шрифта для заголовка экрана",
        "theme" to "Тема",
        "theme_light" to "Светлая",
        "theme_dark" to "Тёмная",
        "theme_system" to "Системная",
        "accent_color" to "Акцентный цвет",
        "save" to "Сохранить",
        "cancel" to "Отмена",
        "delete" to "Удалить",
        "import" to "Импортировать",
        "confirm_import_books" to "Текущая библиотека будет заменена библиотекой из файла.",
        "confirm_import_settings" to "Все текущие настройки приложения будут заменены настройками из файла.",
        "stats" to "Статистика",
        "total_books" to "Всего тайтлов",
        "pages_read" to "Прочитано страниц",
        "chapters_read" to "Прочитано глав",
        "color_settings" to "Настройки цвета",
        "color_customization" to "Кастомизация цветов",
        "color_customization_sub" to "Настроить цвета интерфейса, типов и статусов",
        "advanced_functions" to "Дополнительный функционал",
        "bookmarks" to "Закладки",
        "bookmarks_sub_on" to "Поле введения текущей главы без влияния на статистику",
        "bookmarks_sub_off" to "Поле заметок отключено",
        "bookmark_position" to "Расположение закладки",
        "bookmark_position_sub" to "Положение текущей закладки в списке книг",
        "bottom" to "Снизу",
        "inline" to "В ряд",
        "read_after_adaptation" to "Читать после адаптации",
        "read_after_adaptation_sub_on" to "Возможность указать том/главу, с которых вы начали",
        "read_after_adaptation_sub_off" to "Функция \"Старт после адаптации\" отключена",
        "hybrid_format" to "Гибридный формат LN+WN",
        "hybrid_format_sub_on" to "Позволяет объединить LN и WN в одной карточке",
        "hybrid_format_sub_off" to "Раздельные карточки томов и глав",
        "title_rating" to "Оценка тайтлов",
        "title_rating_sub_on" to "Возможность оценивать тайтлы",
        "title_rating_sub_off" to "Функция выставления оценки отключена",
        "rating_scale" to "Шкала оценки",
        "rating_scale_sub" to "Инструмент шкалы градации оценок",
        "stars_5" to "5 звёзд",
        "stars_10" to "10 звёзд",
        "rating_placement" to "Расположение оценки и типа",
        "rating_placement_sub" to "Выбрать, как располагать оценку и тип на карточке",
        "column" to "В столбик",
        "row" to "В ряд",
        "show_in_analytics" to "Показ в аналитике",
        "show_in_analytics_sub" to "Выбрать, какие типы отображать в отчётах",
        "singles_and_web" to "Синглы и Веб",
        "only_singles" to "Только синглы",
        "only_web" to "Только Веб",
        "hidden" to "Скрыто",
        "title_covers" to "Обложки тайтлов",
        "title_covers_sub_on" to "Показывать обложки в списке",
        "title_covers_sub_off" to "Компактный вид без обложек",
        "shorten_numbers" to "Сокращать числа",
        "shorten_numbers_sub" to "Например: 150K вместо 150 000",
        "stacked_analytics" to "Широкие карточки статистики",
        "stacked_analytics_sub" to "Располагать метрики аналитики друг под другом",
        "share_button" to "Кнопка «Поделиться»",
        "share_button_sub" to "Отображать шторку экспорта в шапке библиотеки",
        "chapters_for_web" to "Главы для Веб-романов",
        "chapters_for_web_sub_on" to "Показывать X/Y гл. на карточках",
        "chapters_for_web_sub_off" to "Прогресс глав скрыт в списке",
        "disable_animations" to "Отключение анимаций",
        "disable_animations_sub_on" to "Анимации переходов выключены",
        "disable_animations_sub_off" to "Плавные переходы между страницами",
        "header_spacing" to "Расстояние от шапки до фильтров",
        "header_spacing_sub" to "Отступ между надписью 'Библиотека' и панелью вкладок",
        "card_spacing" to "Расстояние в карточках",
        "card_spacing_sub" to "Настройка размера и интервала строк внутри карточек",
        "title_font_size" to "Размер названия тайтла",
        "title_font_size_sub" to "Настройка размера шрифта для заголовка на карточке",
        "reset_all" to "Сбросить всё",
        "reset_to_default" to "Сбросить все цвета по умолчанию",
        "color_reset_title" to "Сброс цветовой схемы",
        "color_reset_confirm" to "Вы уверены, что хотите сбросить все кастомные цвета интерфейса, типов изданий и статусов чтения к значениям по умолчанию?",
        "reset" to "Сбросить",
        "close" to "Закрыть",
        "interface_colors" to "Цвета интерфейса",
        "accent_and_buttons" to "Цвет акцента и кнопок",
        "edition_types" to "Типы изданий",
        "reading_statuses" to "Статусы чтения",
        "flexible_customization" to "Гибкая кастомизация",
        "customization_sub" to "Нажмите на цветной кружок, чтобы выбрать цвет из палитры, или введите HEX-значение вручную.",
        "pick_color" to "Выберите цвет",
        "pick_from_palette" to "Выберите из готовой палитры:",
        "save_to_json" to "Сохранить в JSON-файл",
        "load_from_json" to "Загрузить из JSON-файла",
        "save_configuration" to "Сохранить текущую конфигурацию",
        "load_configuration" to "Загрузить конфигурацию из файла",
        "stats_card" to "Карточка со статистикой",
        "title_list" to "Список тайтлов",
        "all_titles_card" to "Все тайтлы в одной карточке"
    )

    fun getString(key: String, lang: String): String {
        return (if (lang == "en") en else ru)[key] ?: key
    }
}
